### ISSUE TITLE
run_seq2tree_APE.py 运行错误

### ISSUE THREAD

**Issue by RingoTC** [qinzhuowu/NumS2T#2]
尚未进行任何修改，运行 run_seq2tree_APE.py 报错如下
start_from_epoch:101
last model acc:0.788
Traceback (most recent call last):
  File "run_seq2tree_APE.py", line 171, in <module>
    encoder.load_state_dict(torch.load("models/encoder"+str(fold)))
  File "/home/....../miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderSeq:
        size mismatch for embedding.weight: copying a param with shape torch.Size([3390, 300]) from checkpoint, the shape in current model is torch.Size([3243, 300]).

**Comment by qinzhuowu** [comment]
models里面的是在Math23K数据集上训练的模型文件。APE210K不能直接load。
delete models/encoder0&epoch_num0&generate0&merge0&predict0后
运行 run_seq2tree_APE.py

**Comment by qinzhuowu** [comment]
你好，run_seq2tree_APE.py是在APE210K数据集上训练的，models里面保存的模型是在Math23K数据集下训练的。
这两个数据集的input_lang，output_lang里面词表的大小和顺序不一样，所以给APE数据集加载Math23K模型会报错。
把models里面的模型删了去运行run_seq2tree_APE.py或者在171行附近把load_state_dict那几行注释掉，都能运行这个文件。




-----原始邮件-----
发件人:"Han Liao" ***@***.***>
发送时间:2021-06-24 17:01:57 (星期四)
收件人: qinzhuowu/NumS2T ***@***.***>
抄送: Subscribed ***@***.***>
主题: [qinzhuowu/NumS2T] run_seq2tree_APE.py 运行错误 (#2)



尚未进行任何修改，运行 run_seq2tree_APE.py 报错如下
start_from_epoch:101
last model acc:0.788
Traceback (most recent call last):
File "run_seq2tree_APE.py", line 171, in
encoder.load_state_dict(torch.load("models/encoder"+str(fold)))
File "/home/....../miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EncoderSeq:
size mismatch for embedding.weight: copying a param with shape torch.Size([3390, 300]) from checkpoint, the shape in current model is torch.Size([3243, 300]).

**Comment by RingoTC** [comment]
好的，感谢回复！
